### ISSUE TITLE
Plagiarism Essay

### ISSUE THREAD

**Issue by nadeld** [Nikki-Luoma/Nikki-Luoma.github.io#17]
I like the start you have especially your topic of the essay which focuses on the music industry. I think you should organize your essay with two paragraphs on the plagiarism in the music industry and two paragraphs on your personal experience. Then have a solution paragraph on how we can enforce plagiarism in the music industry and other ways we can discourage plagiarism.

**Comment by Nikki-Luoma** [comment]
Thank you! My next paragraph is going to be about how I have seen professors copy and paste their quizzes from other websites.

**Comment by nadeld** [comment]
2nd paragraph:
-number 1 song should be changed to number one song
I really like the research that you have here!

3rd paragraph:
-For example, often times teachers or professors will make students take quizzes **that the educators make the illusion that they created it,** yet I have found this to be untrue.  This sentence is a little awkward
-I was puzzled until I look for myself. sentence seems unnecessary
-Students look up to the professors, **and this does not give students the right guidance.** consider changing this 

4th paragraph:
-Despite plagiarism being around students the way to end it is to educate them on the matter. (I would put a comma after students, clean this sentence up)
Good Conclusion!

**Comment by Nikki-Luoma** [comment]
I took what you said into consideration, thank you.
