### ISSUE TITLE
Final Project Article

### ISSUE THREAD

**Issue by nadeld** [Nikki-Luoma/Nikki-Luoma.github.io#18]
1st paragraph- Often times should be one word "Oftentimes".
without thinking of any of their consequence- change to without thinking of the consequences.
"would not but"- change to would not, but it also allows
I would clean up the second sentence, a little bit too lengthy
The internet has not allowed- change to "The internet has allowed"
In this paragraph you have really good ideas, I recommend you talk about piracy, cyberbullying, and people's morals when using the Internet in your body paragraphs.

2nd paragraph-
change hid to hide
Nice job so far!

**Comment by Nikki-Luoma** [comment]
Thank you, I will fix that.

**Comment by nadeld** [comment]
Lastly, you say "Plagiarism is a growing academic crime. " You have already said this earlier in the paragraph and I would consider removing it. 
Also, you say "that last decade", it should be the last decade.
I would just add like one or two closing sentences.

**Comment by Nikki-Luoma** [comment]
Thank you!
